name: PokeCardDetect
dependencies:
  - python
  - numpy
  - pandas
  - pillow
  - imagehash
  - flask
  - gunicorn
  - requests
  - opencv
  - openpyxl
  - pip
  - pip:
    - git+https://github.com/PokemonTCG/pokemon-tcg-sdk-python.git